export default [
  {
    name: "Silver",
    price: "0.00",
    description: "For most businesses that want to optimize web queries",
    isMostPopular: false,
    options: [
      { name: "UI Design", available: true },
      { name: "Web development", available: true },
      { name: "logo design", available: false },
      { name: "Seo optimization", available: false },
      { name: "WordPress integration", available: false },
      { name: "5 Websites", available: false },
      { name: "Unlimited user", available: false },
      { name: "20 GB bandwith", available: false },
    ],
  },
  {
    name: "Gold",
    price: "50.00",
    description: "For most businesses that want to optimize web queries",
    isMostPopular: true,
    options: [
      { name: "UI Design", available: true },
      { name: "Web development", available: true },
      { name: "logo design", available: true },
      { name: "Seo optimization", available: true },
      { name: "WordPress integration", available: false },
      { name: "5 Websites", available: false },
      { name: "Unlimited user", available: false },
      { name: "20 GB bandwith", available: false },
    ],
  },
  {
    name: "dimond",
    price: "80.00",
    description: "For most businesses that want to optimize web queries",
    isMostPopular: false,
    options: [
      { name: "UI Design", available: true },
      { name: "Web development", available: true },
      { name: "logo design", available: true },
      { name: "Seo optimization", available: true },
      { name: "WordPress integration", available: true },
      { name: "5 Websites", available: true },
      { name: "Unlimited user", available: true },
      { name: "20 GB bandwith", available: true },
    ],
  },
];
